services:
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://*:7001
    ports:
        - "7001:7001"
    volumes:
        - identity_volume:/identity.sqlite
  
  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    depends_on:
        - rabbitmq
    environment:
        - ASPNETCORE_URLS=http://*:7002
        - ConnectionStrings__RabbitMQ=rabbitmq
    ports:
        - "7002:7002"
    volumes:
        - payment_volume:/PaymentService.sqlite
    networks:
        - common_network

  notifictationservice:
    image: ${DOCKER_REGISTRY-}notifictationservice
    build:
      context: .
      dockerfile: NotifictationService/Dockerfile
    ports:
        - "7003:7003"
    depends_on:
        - rabbitmq
    environment:
        - ASPNETCORE_URLS=http://*:7003
        - ConnectionStrings__RabbitMQ=rabbitmq
    networks:
        - common_network

  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    depends_on:
        - rabbitmq
        - redis
        - mongo
    ports:
        - "7004:7004"
    environment:
        - ASPNETCORE_URLS=http://*:7004
        - ConnectionStrings__MongoDB=mongodb://mongodb:27017
        - ConnectionStrings__Redis=redis
        - ConnectionStrings__RabbitMQ=rabbitmq
    networks:
        - common_network
  
  redis:
    image: redis:latest
    container_name: dbredis
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    networks:
        - common_network
  
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
        - "27017:27107"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
        - common_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - common_network
    healthcheck:
        test: ["CMD", "curl", "-f", "localhost:15672/"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

volumes:
  identity_volume:
  payment_volume:
  rabbitmq_data:
  mongo-data:
  mongo-config:

networks:
    common_network:
        driver: bridge

