export const ADMIN_ROUTE = "/admin";

export const AUTH_ROUTE = "/auth";
export const REGISTRATION_ROUTE = "register";
export const USER_ROUTE = "/user";
export const SELLER_ROUTE = "/seller";
export const SHOP_ROUTE = "/";
export const BASKET_ROUTE = "/basket";
export const DEVICE_ROUTE = "/product";
export const SELLER_SHOP_ROUTE = "/shop";

export const items = [
  {
    title: "Стол",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Коричневый", "Тёмный коричневый"],
    description: ["Материал — дерево", "Размер — 120x80 см"],
    count: 10,
    LastPrice: 5000,
    Discount: 10,
  },
  {
    title: "Стул",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серый"],
    description: ["Материал — металл", "Вес — 5 кг"],
    count: 15,
    LastPrice: 1500,
    Discount: 5,
  },
  {
    title: "Ноутбук",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Серебристый", "Чёрный"],
    description: ["Материал — алюминий", "Процессор — Intel i7"],
    count: 5,
    LastPrice: 45000,
    Discount: 20,
  },
  {
    title: "Часы",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Золотистый", "Чёрный"],
    description: ["Материал — нержавеющая сталь", "Водозащищённость — 5 ATM"],
    count: 8,
    LastPrice: 12000,
    Discount: 15,
  },
  {
    title: "Кружка",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Белая", "Синяя"],
    description: ["Материал — керамика", "Объём — 300 мл"],
    count: 25,
    LastPrice: 300,
    Discount: 0,
  },
  {
    title: "Телевизор",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серый"],
    description: ["Диагональ — 55 дюймов", "Разрешение — 4K"],
    count: 12,
    LastPrice: 25000,
    Discount: 5,
  },
  {
    title: "Холодильник",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Белый", "Серебристый"],
    description: ["Объём — 300 литров", "Энергопотребление — A+"],
    count: 7,
    LastPrice: 35000,
    Discount: 10,
  },
  {
    title: "Микроволновка",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серебристый"],
    description: ["Мощность — 800 Вт", "Объём — 20 л"],
    count: 20,
    LastPrice: 6000,
    Discount: 8,
  },
  {
    title: "Миксер",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Белый", "Красный"],
    description: ["Мощность — 300 Вт", "Скорости — 5"],
    count: 30,
    LastPrice: 1500,
    Discount: 12,
  },
  {
    title: "Кофемашина",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серебристый"],
    description: ["Объём — 1.5 л", "Мощность — 1500 Вт"],
    count: 6,
    LastPrice: 12000,
    Discount: 15,
  },
  {
    title: "Пылесос",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Красный", "Чёрный"],
    description: ["Мощность — 2000 Вт", "Тип — вертикальный"],
    count: 14,
    LastPrice: 8000,
    Discount: 7,
  },
  {
    title: "Смартфон",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Синий"],
    description: ["Процессор — Snapdragon", "Экран — 6.5 дюймов"],
    count: 18000,
    LastPrice: 25000,
    Discount: 20,
  },
  {
    title: "Клавиатура",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серый"],
    description: ["Тип — механическая", "Подсветка — RGB"],
    count: 22,
    LastPrice: 5000,
    Discount: 10,
  },
  {
    title: "Мышь",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серебристый"],
    description: ["Тип — беспроводная", "Разрешение — 2000 DPI"],
    count: 35,
    LastPrice: 1500,
    Discount: 15,
  },
  {
    title: "Наушники",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Белый"],
    description: ["Тип — накладные", "Звук — стерео"],
    count: 28,
    LastPrice: 3500,
    Discount: 10,
  },
  {
    title: "Рюкзак",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Синий"],
    description: ["Материал — ткань", "Объём — 25 л"],
    count: 40,
    LastPrice: 2000,
    Discount: 12,
  },
  {
    title: "Шлем",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Серый"],
    description: ["Материал — полиуретан", "Размер — универсальный"],
    count: 12,
    LastPrice: 3500,
    Discount: 5,
  },
  {
    title: "Очки",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Чёрный", "Коричневый"],
    description: ["Тип — солнцезащитные", "Ультрафиолетовая защита — UV400"],
    count: 50,
    LastPrice: 1000,
    Discount: 0,
  },
  {
    title: "Ручка",
    img: ["https://via.placeholder.com/150", "https://via.placeholder.com/160"],
    color: ["Синий", "Чёрный"],
    description: ["Тип — шариковая", "Толщина стержня — 0.7 мм"],
    count: 100,
    LastPrice: 50,
    Discount: 5,
  },
];
